Add unused directory/file to workaround local error obligations.blade.php
local.ERROR: Unable to locate a class or view for component [obligations.23.71.obligations]. {"userId":9086}